window.NATIONAL_CRIME_RATE = 3342.9;
window.REGIONS = [
  { id: "seoul", name: "서울", area: "서울특별시", neighborhood: "서울시 · 마포·성동구", tagline: "기회와 취향이 가장 가까운 곳", image: "photo-1519501025264-65ba15a82390", alt: "서울 도심 풍경", photo: "photo-1519501025264-65ba15a82390", icon: "☀", temperature: "연평균 13.0°C", rainfall: "연 강수량 1,410mm", apartment: "12.8억", house: "11.0억", villa: "4.8억", costIndex: 128, monthlyCost: "약 225만 원", economy: "IT·금융·문화콘텐츠·서비스", specialty: "광장시장 먹거리 · 서울식품", disasters: "집중호우 · 폭염 · 한파", location: "수도권 중심, 전국 철도·대중교통망 연결", lat: 37.57, lng: 126.98, mapQuery: "서울특별시", tags: ["nature"], keywords: "수도권 일자리 교통 문화 콘텐츠 도시", description: "일자리와 문화생활, 촘촘한 대중교통이 강점. 동네별 주거비와 생활 분위기를 비교해 보세요.", crimeRate: 3418.2 },
  { id: "busan", name: "부산", area: "부산광역시", neighborhood: "부산시 · 수영·해운대구", tagline: "큰 바다 곁에서 누리는 도시의 에너지", image: "photo-1500375592092-40eb2168fd21", alt: "부산 해안의 푸른 바다", photo: "photo-1500375592092-40eb2168fd21", icon: "☀", temperature: "연평균 15.0°C", rainfall: "연 강수량 1,520mm", apartment: "5.4억", house: "5.1억", villa: "2.5억", costIndex: 105, monthlyCost: "약 180만 원", economy: "해양물류·관광·영화·금융", specialty: "어묵 · 기장 미역", disasters: "태풍 · 해안 침수 · 폭염", location: "남동 해안, KTX 서울에서 약 2시간 40분", lat: 35.18, lng: 129.08, mapQuery: "부산광역시", tags: ["coast", "warm"], keywords: "바다 해변 남쪽 따뜻 도시 해양 항구", description: "해변과 대도시 인프라를 함께 누리는 곳. 동네마다 분위기와 주거비 차이가 커요.", crimeRate: 3845.8 },
  { id: "daegu", name: "대구", area: "대구광역시", neighborhood: "대구시 · 수성·중구", tagline: "익숙한 도심의 편리함과 따뜻한 햇살", image: "photo-1518005020951-eccb494ad742", alt: "도시 중심의 건축물", photo: "photo-1518005020951-eccb494ad742", icon: "☀", temperature: "연평균 14.1°C", rainfall: "연 강수량 1,030mm", apartment: "4.0억", house: "3.5억", villa: "1.9억", costIndex: 99, monthlyCost: "약 163만 원", economy: "의료·첨단섬유·로봇·자동차부품", specialty: "사과 · 막창 · 납작만두", disasters: "폭염 · 집중호우 · 한파", location: "영남 내륙 중심, KTX 동대구역 생활권", lat: 35.87, lng: 128.60, mapQuery: "대구광역시", tags: ["affordable", "warm"], keywords: "따뜻 햇살 내륙 의료 섬유 영남", description: "지하철과 생활 인프라를 갖춘 영남권 대도시. 여름 더위와 동네별 주거비를 확인해 보세요.", crimeRate: 3197.5 },
  { id: "incheon", name: "인천", area: "인천광역시", neighborhood: "인천시 · 송도·부평구", tagline: "바다와 국제도시의 가능성이 만나는 곳", image: "photo-1519608487953-e999c86e7455", alt: "해안 도시의 풍경", photo: "photo-1519608487953-e999c86e7455", icon: "⛅", temperature: "연평균 12.8°C", rainfall: "연 강수량 1,150mm", apartment: "5.0억", house: "4.1억", villa: "2.3억", costIndex: 103, monthlyCost: "약 172만 원", economy: "물류·바이오·항공·국제업무", specialty: "강화섬쌀 · 꽃게 · 순무김치", disasters: "태풍 · 해안 침수 · 폭염", location: "수도권 서부, 인천국제공항·서울 지하철 연결", lat: 37.46, lng: 126.71, mapQuery: "인천광역시", tags: ["coast", "nature"], keywords: "바다 공항 국제도시 수도권 송도", description: "공항과 항만, 수도권 교통망을 두루 갖췄어요. 신도시와 원도심의 생활 환경은 다를 수 있습니다.", crimeRate: 3289.1 },
  { id: "gwangju", name: "광주", area: "광주광역시", neighborhood: "광주시 · 상무·첨단지구", tagline: "문화와 정이 살아 있는 호남의 중심", image: "photo-1500530855697-b586d89ba3ee", alt: "도심 가까이 펼쳐진 자연 풍경", photo: "photo-1500530855697-b586d89ba3ee", icon: "☀", temperature: "연평균 14.0°C", rainfall: "연 강수량 1,390mm", apartment: "3.5억", house: "3.2억", villa: "1.7억", costIndex: 96, monthlyCost: "약 158만 원", economy: "자동차·에너지·문화콘텐츠", specialty: "무등산수박 · 김치 · 오리탕", disasters: "집중호우 · 폭염 · 대설", location: "호남 내륙 중심, 광주송정역 KTX 생활권", lat: 35.16, lng: 126.85, mapQuery: "광주광역시", tags: ["affordable", "warm"], keywords: "문화 예술 미식 따뜻 호남", description: "풍부한 문화예술과 먹거리, 비교적 합리적인 주거비가 매력인 호남권 중심 도시예요.", crimeRate: 3434.6 },
  { id: "daejeon", name: "대전", area: "대전광역시", neighborhood: "대전시 · 유성·서구", tagline: "어디든 가깝고, 내일이 기대되는 도시", image: "photo-1519501025264-65ba15a82390", alt: "도시의 거리와 건물", photo: "photo-1519501025264-65ba15a82390", icon: "⛅", temperature: "연평균 13.0°C", rainfall: "연 강수량 1,350mm", apartment: "4.5억", house: "4.0억", villa: "2.2억", costIndex: 98, monthlyCost: "약 165만 원", economy: "연구개발·바이오·국방", specialty: "성심당 빵 · 유성 온천", disasters: "집중호우 · 폭염 · 대설", location: "대한민국 중심부, KTX 서울에서 약 1시간", lat: 36.35, lng: 127.38, mapQuery: "대전광역시", tags: ["nature", "affordable"], keywords: "교통 연구 일자리 과학 중부 생활 편리", description: "사통팔달 교통과 탄탄한 연구·일자리 기반. 도심 가까이에서도 녹지를 쉽게 만날 수 있어요.", crimeRate: 3317.8 },
  { id: "ulsan", name: "울산", area: "울산광역시", neighborhood: "울산시 · 남구·중구", tagline: "산업의 활력과 바다·산의 여유", image: "photo-1501785888041-af3ef285b470", alt: "산과 물이 어우러진 자연", photo: "photo-1501785888041-af3ef285b470", icon: "☀", temperature: "연평균 14.1°C", rainfall: "연 강수량 1,290mm", apartment: "4.2억", house: "4.0억", villa: "2.0억", costIndex: 102, monthlyCost: "약 170만 원", economy: "자동차·조선·석유화학·수소", specialty: "언양불고기 · 배 · 돌미역", disasters: "태풍 · 해안 침수 · 산불", location: "동남 해안, KTX 울산역과 도심 버스 연결", lat: 35.54, lng: 129.31, mapQuery: "울산광역시", tags: ["coast", "nature", "warm"], keywords: "산업 일자리 바다 따뜻 동남 해안", description: "제조업 일자리와 넓은 자연 공간이 함께 있어요. 도심과 KTX역 사이 이동 거리를 살펴보세요.", crimeRate: 1727.4 },
  { id: "sejong", name: "세종", area: "세종특별자치시", neighborhood: "세종시 · 나성·어진동", tagline: "계획도시의 쾌적함과 새로운 일상", image: "photo-1518005020951-eccb494ad742", alt: "현대적인 도시 건축 풍경", photo: "photo-1518005020951-eccb494ad742", icon: "⛅", temperature: "연평균 12.8°C", rainfall: "연 강수량 1,250mm", apartment: "6.0억", house: "4.7억", villa: "2.6억", costIndex: 104, monthlyCost: "약 175만 원", economy: "행정·공공기관·스마트시티", specialty: "복숭아 · 조치원 배", disasters: "집중호우 · 폭염 · 대설", location: "충청권 중심, BRT·오송역 연계", lat: 36.48, lng: 127.29, mapQuery: "세종특별자치시", tags: ["nature"], keywords: "행정 신도시 쾌적 공공기관 가족", description: "계획적으로 조성된 생활권과 공원·자전거길이 장점. 대중교통과 주거비는 생활권별로 확인하세요.", crimeRate: 2335.3 },
  { id: "gyeonggi", name: "경기", area: "경기도", neighborhood: "수원·성남·고양 등", tagline: "도시마다 다른 선택지가 가득한 수도권", image: "photo-1519608487953-e999c86e7455", alt: "넓게 이어지는 도시 풍경", photo: "photo-1519501025264-65ba15a82390", icon: "⛅", temperature: "연평균 12.5°C", rainfall: "연 강수량 1,300mm", apartment: "6.5억", house: "5.8억", villa: "2.9억", costIndex: 111, monthlyCost: "약 190만 원", economy: "반도체·IT·바이오·제조업", specialty: "이천쌀 · 여주쌀 · 포천 이동갈비", disasters: "집중호우 · 폭염 · 한파", location: "수도권 전역, 서울과 광역철도·버스로 연결", lat: 37.27, lng: 127.01, mapQuery: "경기도", tags: ["nature"], keywords: "수도권 반도체 일자리 교통 신도시", description: "산업과 일자리, 주거 선택지가 다양한 광역 생활권. 시·군별 통근 시간과 집값 편차가 큽니다.", crimeRate: 3201.5 },
  { id: "gangwon", name: "강원", area: "강원특별자치도", neighborhood: "춘천·강릉·원주 등", tagline: "산과 바다가 가까운 자연 속 생활", image: "photo-1501785888041-af3ef285b470", alt: "산과 호수가 펼쳐진 풍경", photo: "photo-1473116763249-2faaef81ccda", icon: "❄", temperature: "연평균 11.5°C", rainfall: "연 강수량 1,340mm", apartment: "3.5억", house: "3.2억", villa: "1.7억", costIndex: 93, monthlyCost: "약 152만 원", economy: "관광·바이오·의료·공공기관", specialty: "감자 · 옥수수 · 초당두부", disasters: "폭설 · 산불 · 집중호우", location: "영서·영동 생활권, 도시별 수도권 접근성 상이", lat: 37.88, lng: 127.73, mapQuery: "강원특별자치도", tags: ["coast", "nature", "affordable"], keywords: "호수 산 바다 자연 조용 한적 저렴 강릉 춘천 원주", description: "호수·산·동해가 함께 있는 넓은 지역. 춘천·원주·강릉 등 도시마다 기후와 교통이 다릅니다.", crimeRate: 3287.6 },
  { id: "chungbuk", name: "충북", area: "충청북도", neighborhood: "청주시 · 흥덕·상당구", tagline: "내륙의 편리한 교통과 여유로운 생활", image: "photo-1500530855697-b586d89ba3ee", alt: "초록 들판과 산이 보이는 풍경", photo: "photo-1501785888041-af3ef285b470", icon: "☀", temperature: "연평균 12.5°C", rainfall: "연 강수량 1,200mm", apartment: "3.3억", house: "3.0억", villa: "1.6억", costIndex: 92, monthlyCost: "약 150만 원", economy: "바이오·반도체·이차전지·제약", specialty: "괴산 고추 · 충주 사과", disasters: "집중호우 · 대설 · 한파", location: "내륙 교통 요충지, 청주공항·오송역 이용", lat: 36.64, lng: 127.49, mapQuery: "충청북도 청주시", tags: ["nature", "affordable"], keywords: "청주 내륙 저렴 바이오 반도체 자연", description: "청주를 중심으로 산업단지와 생활 인프라가 발달했어요. 내륙 특성상 여름·겨울 기온차가 큽니다.", crimeRate: 3067.5 },
  { id: "chungnam", name: "충남", area: "충청남도", neighborhood: "천안·아산·공주 등", tagline: "산업도시와 바닷가, 다양한 삶의 반경", image: "photo-1473116763249-2faaef81ccda", alt: "넓은 들판과 푸른 하늘", photo: "photo-1500530855697-b586d89ba3ee", icon: "☀", temperature: "연평균 12.8°C", rainfall: "연 강수량 1,230mm", apartment: "3.4억", house: "3.1억", villa: "1.7억", costIndex: 94, monthlyCost: "약 153만 원", economy: "자동차·디스플레이·철강·농업", specialty: "금산 인삼 · 서산 생강 · 태안 꽃게", disasters: "집중호우 · 폭염 · 대설", location: "수도권 남부·충청권, 천안아산역 KTX 연결", lat: 36.66, lng: 126.67, mapQuery: "충청남도", tags: ["coast", "affordable"], keywords: "천안 아산 바다 산업 저렴 농업", description: "천안·아산의 산업·교통과 서해안의 자연을 함께 품은 곳. 시·군 사이 이동 거리를 고려하세요.", crimeRate: 3427.6 },
  { id: "jeonbuk", name: "전북", area: "전북특별자치도", neighborhood: "전주시 · 완산·덕진구", tagline: "좋은 먹거리와 넉넉한 동네의 온기", image: "photo-1518005020951-eccb494ad742", alt: "전통과 현대가 어우러진 거리", photo: "photo-1500530855697-b586d89ba3ee", icon: "☀", temperature: "연평균 14.0°C", rainfall: "연 강수량 1,320mm", apartment: "3.3억", house: "3.2억", villa: "1.6억", costIndex: 90, monthlyCost: "약 145만 원", economy: "식품·문화관광·농생명·탄소소재", specialty: "전주비빔밥 · 한지 · 군산 꽃게장", disasters: "집중호우 · 폭염 · 대설", location: "호남 내륙, KTX 전주역·익산역 이용", lat: 35.82, lng: 127.15, mapQuery: "전북특별자치도 전주시", tags: ["nature", "affordable", "warm"], keywords: "전통 한옥 먹거리 음식 따뜻 저렴 문화 전주", description: "풍성한 미식 문화와 비교적 낮은 생활비가 매력. 전주·군산·익산 등 도시별 특성이 달라요.", crimeRate: 3256.2 },
  { id: "jeonnam", name: "전남", area: "전라남도", neighborhood: "여수·순천·목포 등", tagline: "남도의 바다와 풍요로운 먹거리", image: "photo-1500375592092-40eb2168fd21", alt: "남쪽 해안의 푸른 바다", photo: "photo-1473116763249-2faaef81ccda", icon: "☀", temperature: "연평균 14.5°C", rainfall: "연 강수량 1,390mm", apartment: "2.8억", house: "3.0억", villa: "1.5억", costIndex: 91, monthlyCost: "약 148만 원", economy: "에너지·석유화학·조선·농수산업", specialty: "갓김치 · 매실 · 굴비 · 꼬막", disasters: "태풍 · 집중호우 · 해안 침수", location: "남서 해안, 시·군별 철도·도로 접근성 차이", lat: 34.76, lng: 127.66, mapQuery: "전라남도", tags: ["coast", "nature", "affordable", "warm"], keywords: "바다 섬 따뜻 남도 미식 저렴 여수 순천 목포", description: "긴 해안선과 풍부한 농수산물, 온화한 기후가 특징. 도시 간 이동과 의료·교통 여건을 확인하세요.", crimeRate: 3859.8 },
  { id: "gyeongbuk", name: "경북", area: "경상북도", neighborhood: "경주·포항·안동 등", tagline: "깊은 역사와 자연이 가까운 일상", image: "photo-1500530855697-b586d89ba3ee", alt: "산과 들이 어우러진 경북 풍경", photo: "photo-1501785888041-af3ef285b470", icon: "☀", temperature: "연평균 12.8°C", rainfall: "연 강수량 1,090mm", apartment: "2.9억", house: "3.1억", villa: "1.5억", costIndex: 92, monthlyCost: "약 150만 원", economy: "철강·전자·자동차부품·관광", specialty: "영주 사과 · 안동 간고등어 · 경주빵", disasters: "산불 · 태풍 · 지진", location: "동해안·내륙에 걸친 넓은 지역, KTX역 분산", lat: 36.57, lng: 128.73, mapQuery: "경상북도", tags: ["coast", "nature", "affordable"], keywords: "역사 문화 유적 따뜻 저렴 조용 경주 포항 안동", description: "경주·포항·안동 등 역사와 산업이 어우러져요. 지역이 넓어 거주 도시를 기준으로 교통을 살펴보세요.", crimeRate: 3253.2 },
  { id: "gyeongnam", name: "경남", area: "경상남도", neighborhood: "창원·진주·거제 등", tagline: "산업의 기회와 남해의 풍경", image: "photo-1500375592092-40eb2168fd21", alt: "남해안 바다 풍경", photo: "photo-1501785888041-af3ef285b470", icon: "☀", temperature: "연평균 14.0°C", rainfall: "연 강수량 1,470mm", apartment: "3.5억", house: "3.4억", villa: "1.8억", costIndex: 97, monthlyCost: "약 160만 원", economy: "기계·조선·항공·방산·자동차", specialty: "통영 굴 · 진주 실크 · 남해 마늘", disasters: "태풍 · 집중호우 · 산불", location: "남동 해안권, 부산·대구와 광역 교통 연결", lat: 35.23, lng: 128.68, mapQuery: "경상남도", tags: ["coast", "nature", "warm"], keywords: "바다 산업 일자리 따뜻 남해 창원 진주 거제", description: "기계·조선 등 산업 일자리와 남해안 자연이 공존. 도시별 산업·통근 여건을 확인하는 게 좋아요.", crimeRate: 3714.6 },
  { id: "jeju", name: "제주", area: "제주특별자치도", neighborhood: "제주시·서귀포시", tagline: "섬의 풍경을 매일의 배경으로", image: "photo-1473116763249-2faaef81ccda", alt: "제주의 푸른 바다와 자연", photo: "photo-1500375592092-40eb2168fd21", icon: "☀", temperature: "연평균 16.2°C", rainfall: "연 강수량 1,500mm", apartment: "4.3억", house: "5.2억", villa: "2.2억", costIndex: 109, monthlyCost: "약 188만 원", economy: "관광·농업·청정에너지", specialty: "감귤 · 흑돼지 · 한라봉", disasters: "태풍 · 호우 · 강풍", location: "대한민국 남쪽 섬, 제주국제공항 생활권", lat: 33.50, lng: 126.53, mapQuery: "제주특별자치도", tags: ["coast", "nature", "warm"], keywords: "섬 바다 따뜻 감귤 자연 이주 제주살이", description: "온화한 기후와 독특한 자연환경. 섬 안에서도 지역마다 교통·생활 편의 차이가 있어요.", crimeRate: 4539.6 }
];

window.LOCAL_AREAS = {
  seoul: ["성수동", "연남동", "한남동", "북촌한옥마을", "익선동", "망원동", "잠실·석촌호수", "이태원·경리단길", "광화문·서촌"],
  busan: ["해운대·달맞이길", "광안리·민락동", "전포카페거리", "남포동·자갈치시장", "송정해수욕장·송정동", "감천문화마을", "흰여울문화마을·영도", "동래온천·명륜동", "기장읍·오시리아"],
  daegu: ["동성로", "수성못·수성구", "앞산카페거리", "서문시장·대신동", "김광석거리·대봉동", "팔공산·동화사", "동촌유원지", "계산동·근대골목", "칠성시장·칠성동"],
  incheon: ["송도국제도시", "차이나타운·개항장", "월미도·영종도", "부평 문화의거리", "소래포구·논현동", "신포동·신포국제시장", "청라국제도시", "강화읍·전등사", "을왕리해수욕장·용유동"],
  gwangju: ["양림동", "동명동", "상무지구", "충장로·금남로", "1913송정역시장·송정동", "국립아시아문화전당 일대", "풍암호수공원·풍암동", "운암동·중외공원", "첨단지구·쌍암동"],
  daejeon: ["둔산동", "은행동·대흥동", "유성온천·봉명동", "대전역·중앙시장", "도룡동·엑스포과학공원", "한밭수목원·만년동", "갈마동·갈리단길", "관평동·테크노밸리", "대청호·대청동"],
  ulsan: ["삼산동", "태화강·태화동", "장생포 고래문화마을", "대왕암공원·일산동", "울산대공원·옥동", "간절곶·서생면", "주전몽돌해변·주전동", "언양읍성·언양시장", "진하해수욕장·서생면"],
  sejong: ["나성동", "어진동", "조치원읍", "세종호수공원·도담동", "국립세종수목원·중앙공원", "보람동·시청 일대", "새롬동·다정동", "고운동·아름동", "금강보행교·한솔동"],
  gyeonggi: ["판교테크노밸리", "수원 행궁동", "동탄호수공원 일대", "분당 정자동·서현동", "광교호수공원·이의동", "일산호수공원·정발산동", "파주 헤이리·탄현면", "의정부 행복로·의정부동", "안산 중앙동·고잔동"],
  gangwon: ["강릉 안목·경포", "춘천 명동·소양강", "원주 혁신도시·기업도시", "속초 중앙시장·영랑동", "양양 서피비치·현남면", "평창 대관령·횡계리", "삼척 장호항·장호리", "고성 아야진·토성면", "원주 단계동·무실동"],
  chungbuk: ["청주 성안길·수암골", "충주 중앙탑·호수", "제천 의림지", "청남대·문의면", "단양 구인사·온달관광지", "충주 수안보온천", "옥천 구읍·정지용생가", "괴산 산막이옛길", "보은 속리산·법주사"],
  chungnam: ["천안 불당동", "아산 온양온천", "공주 공산성·제민천", "보령 대천해수욕장·대천동", "태안 안면도·꽃지해변", "부여 궁남지·부여읍", "논산 탑정호·시민공원", "아산 지중해마을·탕정면", "예산 예당호·출렁다리"],
  jeonbuk: ["전주 한옥마을·객리단길", "군산 시간여행마을", "익산 미륵사지·영등동", "남원 광한루원·요천", "부안 변산반도·격포항", "무주 덕유산리조트·설천면", "김제 벽골제·금산면", "정읍 내장산·쌍화차거리", "완주 삼례문화예술촌·삼례읍"],
  jeonnam: ["여수 이순신광장·낭만포차", "순천만국가정원·조례동", "목포 근대역사문화거리·평화광장", "담양 죽녹원·메타세쿼이아길", "보성 녹차밭·보성읍", "해남 땅끝마을·송지면", "고흥 나로우주센터·봉래면", "완도 명사십리해수욕장·신지면", "곡성 섬진강기차마을·오곡면"],
  gyeongbuk: ["경주 황리단길", "포항 영일대·죽도시장", "안동 하회마을·월영교", "문경새재·문경읍", "영주 부석사·선비촌", "청도 와인터널·청도읍", "울릉 도동항·저동항", "영덕 강구항·대게거리", "구미 금오산·금리단길"],
  gyeongnam: ["창원 상남동·용지호수", "통영 동피랑·강구안", "진주성·평거동", "거제 바람의언덕·도장포", "남해 독일마을·물건리", "합천 해인사·가야면", "산청 동의보감촌·금서면", "밀양 영남루·내일동", "사천 삼천포항·케이블카"],
  jeju: ["제주 연동·노형동", "애월읍 애월리·한담해안", "서귀포 중문관광단지·서귀동", "한림읍 협재해수욕장·금능리", "성산읍 성산일출봉·광치기해변", "조천읍 함덕해수욕장·함덕리", "표선해수욕장·표선리", "구좌읍 월정리·세화리", "한경면 신창풍차해안·저지리"]
};
