const BREEDS = [
  {
    id: "chihuahua",
    name: "치와와",
    en: "Chihuahua",
    size: "소형",
    height: "15~23cm",
    weight: "1.5~3kg",
    life: "12~20년",
    personality: "애착이 강하고 용감하며 주인에게 매우 충성스러움",
    desc: "세계에서 가장 작은 견종으로, 작은 몸에도 큰 용기와 자신감을 지녔습니다. 주인과의 유대가 깊어 실내 반려견으로 인기가 많습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "애교많은", "충성심", "경계심강함", "감시견", "단모", "짖는", "초보자적합", "장수"],
    imgPath: "chihuahua"
  },
  {
    id: "maltese",
    name: "말티즈",
    en: "Maltese",
    size: "소형",
    height: "20~25cm",
    weight: "2~4kg",
    life: "12~15년",
    personality: "애교가 넘치고 밝으며 사람과 함께 있는 것을 좋아함",
    desc: "흰 실크 같은 긴 털이 매력적인 대표적인 실내견입니다. 애교가 많고 사람에게 잘 어울려 노약자에게도 좋은 반려견입니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "애교많은", "장모", "손질필요", "흰털", "사교적인", "온순한", "초보자적합", "아이와잘맞음"],
    imgPath: null
  },
  {
    id: "shih-tzu",
    name: "시츄",
    en: "Shih Tzu",
    size: "소형",
    height: "20~28cm",
    weight: "4~7kg",
    life: "10~16년",
    personality: "온화하고 애정이 많으며 느긋한 성격",
    desc: "중국 황실에서 귀하게 키우던 견종으로, 사자 같은 얼굴과 긴 털이 특징입니다. 성격이 온화해 가정견으로 매우 인기가 많습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "애교많은", "장모", "손질필요", "온순한", "느긋한", "사교적인", "초보자적합", "아이와잘맞음"],
    imgPath: "shihtzu"
  },
  {
    id: "pekingese",
    name: "페키니즈",
    en: "Pekingese",
    size: "소형",
    height: "15~23cm",
    weight: "3~6kg",
    life: "12~15년",
    personality: "품위 있고 독립적이며 주인에게 깊은 애정을 보임",
    desc: "고대 중국 궁정에서 사랑받던 견종으로, 사자 얼굴과 풍성한 갈기가 특징입니다. 점잖고 느긋하며 실내에서 차분하게 지냅니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "장모", "손질필요", "독립적", "느긋한", "조용한", "단두종", "온순한"],
    imgPath: "pekinese"
  },
  {
    id: "papillon",
    name: "파피용",
    en: "Papillon",
    size: "소형",
    height: "20~28cm",
    weight: "2~5kg",
    life: "12~16년",
    personality: "총명하고 활발하며 학습 능력이 매우 뛰어남",
    desc: "나비처럼 펼쳐진 큰 귀가 특징적인 견종으로, 지능이 매우 높아 여러 견기 대회에서 우승하는 등 훈련이 잘 됩니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "똑똑한", "지능높음", "훈련잘됨", "활동적", "장모", "손질필요", "사교적인"],
    imgPath: "papillon"
  },
  {
    id: "poodle",
    name: "푸들",
    en: "Poodle",
    size: "소형",
    height: "24~60cm(크기별 상이)",
    weight: "3~30kg(크기별 상이)",
    life: "12~18년",
    personality: "매우 총명하고 사교적이며 활발함",
    desc: "견종 지능 순위 2위로 학습 능력이 뛰어나고 털빠짐이 거의 없어 알레르기 걱정이 적습니다. 장난기와 애교가 넘칩니다.",
    tags: ["소형", "중형", "아파트적합", "실내적합", "똑똑한", "지능높음", "훈련잘됨", "털잘안빠짐", "활동적", "사교적인", "애교많은", "장난기", "초보자적합", "아이와잘맞음", "귀여운"],
    imgPath: null
  },
  {
    id: "pomeranian",
    name: "포메라니안",
    en: "Pomeranian",
    size: "소형",
    height: "18~24cm",
    weight: "1.5~3.5kg",
    life: "12~16년",
    personality: "활발하고 명랑하며 자신감이 넘침",
    desc: "풍성한 갈기 털과 여우 같은 얼굴이 매력적인 견종입니다. 호기심이 많고 활발하며, 주인에게 애교가 매우 많습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "애교많은", "장모", "손질필요", "활동적", "장난기", "경계심강함", "짖는"],
    imgPath: "pomeranian"
  },
  {
    id: "yorkshire-terrier",
    name: "요크셔테리어",
    en: "Yorkshire Terrier",
    size: "소형",
    height: "18~23cm",
    weight: "2~3.5kg",
    life: "13~16년",
    personality: "용감하고 호기심이 많으며 애착이 강함",
    desc: "실크처럼 매끈한 강철블루 털이 특징입니다. 작지만 용감하고 활발하며, 옛날에는 쥐 사냥개로 활동했습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "장모", "손질필요", "용감한", "활동적", "경계심강함", "짖는", "장난기"],
    imgPath: "terrier/yorkshire"
  },
  {
    id: "bichon-frise",
    name: "비숑프리제",
    en: "Bichon Frise",
    size: "소형",
    height: "23~30cm",
    weight: "3~6kg",
    life: "12~18년",
    personality: "밝고 장난기가 많으며 사람을 좋아함",
    desc: "폭신한 흰 솜사탕 같은 외모로 유명한 견종입니다. 털빠짐이 적고 밝고 긍정적인 성격으로 가정견으로 인기가 많습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "털잘안빠짐", "장모", "손질필요", "흰털", "사교적인", "애교많은", "장난기", "초보자적합", "아이와잘맞음"],
    imgPath: "frise/bichon"
  },
  {
    id: "dachshund",
    name: "닥스훈트",
    en: "Dachshund",
    size: "소형",
    height: "20~27cm",
    weight: "4~12kg",
    life: "12~16년",
    personality: "용감하고 애착이 강하며 다소 고집이 셈",
    desc: "긴 몸과 짧은 다리가 특징으로, 오소리 사냥을 위해 개량된 견종입니다. 호기심 많고 용감하며 주인에게 깊이 애착을 보입니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "귀여운", "용감한", "사냥본능", "활동적", "고집센", "경계심강함", "장수", "장난기"],
    imgPath: null
  },
  {
    id: "min-pin",
    name: "미니어처핀셔",
    en: "Miniature Pinscher",
    size: "소형",
    height: "25~30cm",
    weight: "4~6kg",
    life: "12~16년",
    personality: "에너지가 넘치고 대담하며 호기심이 많음",
    desc: "'댄싱 독'이라 불릴 만큼 활달한 걸음걸이가 매력입니다. 작은 몸에 큰 개의 기질을 지녔고 경계심이 강합니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "단모", "활동적", "용감한", "경계심강함", "감시견", "에너지넘침", "고집센"],
    imgPath: "pinscher/miniature"
  },
  {
    id: "schnauzer",
    name: "슈나우저",
    en: "Schnauzer",
    size: "소형",
    height: "30~50cm(크기별 상이)",
    weight: "5~45kg(크기별 상이)",
    life: "12~16년",
    personality: "총명하고 경계심이 강하며 주인에게 충성스러움",
    desc: "수염과 눈썹이 특징적인 견종으로, 털빠짐이 적어 실내견으로 적합합니다. 총명하고 경계심이 강해 감시견으로도 좋습니다.",
    tags: ["소형", "중형", "대형", "아파트적합", "실내적합", "털잘안빠짐", "똑똑한", "지능높음", "경계심강함", "감시견", "충성심", "활동적", "손질필요"],
    imgPath: null
  },
  {
    id: "boston-terrier",
    name: "보스턴테리어",
    en: "Boston Terrier",
    size: "소형",
    height: "38~43cm",
    weight: "6~11kg",
    life: "11~15년",
    personality: "밝고 사교적이며 온순해 훈련이 잘 됨",
    desc: "'미국 신사'라 불리는 견종으로, 흑백 턱시도 같은 털색이 특징입니다. 사교적이고 온순해 도시 생활에 잘 맞습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "단모", "단두종", "사교적인", "온순한", "훈련잘됨", "아이와잘맞음", "가족친화적", "장난기"],
    imgPath: "terrier/boston"
  },
  {
    id: "west-highland",
    name: "웨스트하이랜드화이트테리어",
    en: "West Highland White Terrier",
    size: "소형",
    height: "25~28cm",
    weight: "6~10kg",
    life: "13~16년",
    personality: "명랑하고 자신감 있으며 활발함",
    desc: "눈처럼 하얀 털의 테리어로, 밝고 유쾌한 성격입니다. 활동적이고 장난기가 많아 아이들과도 잘 지냅니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "흰털", "활동적", "장난기", "용감한", "사교적인", "아이와잘맞음", "털잘안빠짐"],
    imgPath: "terrier/westhighland"
  },
  {
    id: "lhasa-apso",
    name: "라사압소",
    en: "Lhasa Apso",
    size: "소형",
    height: "25~28cm",
    weight: "5~8kg",
    life: "12~18년",
    personality: "독립적이고 경계심이 강하며 겉보기보다 대담함",
    desc: "티베트의 수도원 감시견 출신으로, 긴 털이 특징입니다. 독립적이고 경계심이 강해 좋은 감시견이 됩니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "장모", "손질필요", "경계심강함", "감시견", "독립적", "장수"],
    imgPath: "lhasa"
  },
  {
    id: "italian-greyhound",
    name: "이탈리안그레이하운드",
    en: "Italian Greyhound",
    size: "소형",
    height: "32~38cm",
    weight: "3~5kg",
    life: "12~15년",
    personality: "온화하고 애착이 강하며 민감함",
    desc: "미니어처 그레이하운드로 우아한 실루엣이 매력입니다. 순하고 조용해 실내에서 차분하게 지내며 주인에게 애착이 깊습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "단모", "털잘안빠짐", "온순한", "조용한", "빠름", "민감한", "애교많은"],
    imgPath: "greyhound/italian"
  },
  {
    id: "french-bulldog",
    name: "프렌치불독",
    en: "French Bulldog",
    size: "소형",
    height: "28~33cm",
    weight: "8~14kg",
    life: "10~13년",
    personality: "애교가 많고 온순하며 사람을 좋아함",
    desc: "박쥐 귀와 주름진 얼굴이 매력적인 단두종입니다. 운동량이 적고 조용해 아파트 반려견으로 세계적으로 인기가 많습니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "단모", "단두종", "귀여운", "애교많은", "온순한", "조용한", "운동량적음", "사교적인", "아이와잘맞음"],
    imgPath: "bulldog/french"
  },
  {
    id: "pug",
    name: "퍼그",
    en: "Pug",
    size: "소형",
    height: "25~30cm",
    weight: "6~8kg",
    life: "12~15년",
    personality: "매우 다정하고 온순하며 유머러스함",
    desc: "주름진 얼굴과 동그란 눈이 특징입니다. 차분하고 애교가 많으며, 느긋한 성격 덕분에 가족들과 잘 어울리는 실내견입니다.",
    tags: ["소형", "소형견", "아파트적합", "실내적합", "단모", "단두종", "귀여운", "애교많은", "온순한", "느긋한", "운동량적음", "아이와잘맞음", "가족친화적"],
    imgPath: "pug"
  },
  {
    id: "beagle",
    name: "비글",
    en: "Beagle",
    size: "중형",
    height: "33~41cm",
    weight: "9~14kg",
    life: "12~15년",
    personality: "밝고 사교적이며 호기심과 사냥 본능이 강함",
    desc: "천구(天狗) 같은 긴 귀가 특징이며 뛰어난 후각의 사냥견 출신입니다. 밝고 다정하며 아이와 잘 지내지만 후각에 이끌려 산책 시 주의가 필요합니다.",
    tags: ["중형", "중형견", "아파트적합", "사교적인", "아이와잘맞음", "가족친화적", "활동적", "사냥본능", "후각", "단모", "장수", "장난기"],
    imgPath: "beagle"
  },
  {
    id: "welsh-corgi",
    name: "웰시코기",
    en: "Pembroke Welsh Corgi",
    size: "중형",
    height: "25~30cm",
    weight: "10~14kg",
    life: "12~15년",
    personality: "총명하고 밝으며 활발하고 충성심이 강함",
    desc: "짧은 다리와 풍성한 엉덩이 털이 매력적인 영국 왕실 애견입니다. 지능이 높아 훈련이 잘 되고, 가축 몰이견 출신으로 활동적입니다.",
    tags: ["중형", "중형견", "아파트적합", "실내적합", "귀여운", "똑똑한", "지능높음", "훈련잘됨", "활동적", "충성심", "장모", "털많이빠짐", "장난기", "아이와잘맞음"],
    imgPath: "pembroke"
  },
  {
    id: "cocker-spaniel",
    name: "코커스파니엘",
    en: "Cocker Spaniel",
    size: "중형",
    height: "36~43cm",
    weight: "10~14kg",
    life: "12~15년",
    personality: "다정하고 사교적이며 애정이 풍부함",
    desc: "부드럽게 흘러내리는 귀 털이 아름다운 견종입니다. 온순하고 다정하며 사람을 좋아해 훈련도 잘 따릅니다.",
    tags: ["중형", "중형견", "아파트적합", "장모", "손질필요", "온순한", "사교적인", "애교많은", "아이와잘맞음", "가족친화적", "사냥본능", "활동적"],
    imgPath: "spaniel/cocker"
  },
  {
    id: "shiba",
    name: "시바견",
    en: "Shiba Inu",
    size: "중형",
    height: "35~41cm",
    weight: "8~11kg",
    life: "12~15년",
    personality: "독립적이고 씩씩하며 다소 고집이 셈",
    desc: "일본의 작은 사냥개로, 여우 같은 얼굴과 말린 꼬리가 특징입니다. 독립적이고 깨끗한 성격이지만 고집이 강해 꾸준한 훈련이 필요합니다.",
    tags: ["중형", "중형견", "단모", "독립적", "고집센", "활동적", "경계심강함", "사냥본능", "충성심", "장난기", "털많이빠짐"],
    imgPath: "shiba"
  },
  {
    id: "akita",
    name: "아키타견",
    en: "Akita",
    size: "대형",
    height: "58~70cm",
    weight: "30~55kg",
    life: "10~15년",
    personality: "충성심이 극도로 강하고 차분하며 경계심이 많음",
    desc: "일본의 국견으로 충견 하치코의 주인공입니다. 주인에 대한 충성심이 매우 강하고 침착하지만 낯선 사람에게는 경계심이 강합니다.",
    tags: ["대형", "대형견", "충성심", "경계심강함", "감시견", "단모", "차분한", "독립적", "털많이빠짐", "용감한"],
    imgPath: "akita"
  },
  {
    id: "english-bulldog",
    name: "잉글리시불독",
    en: "English Bulldog",
    size: "중형",
    height: "31~40cm",
    weight: "18~25kg",
    life: "8~12년",
    personality: "느긋하고 다정하며 고집스럽지만 애정이 깊음",
    desc: "주름진 얼굴과 낮고 튼튼한 몸이 특징입니다. 운동량이 매우 적고 느긋해 실내 생활에 적합하며, 유머러스한 모습으로 사랑받습니다.",
    tags: ["중형", "중형견", "아파트적합", "실내적합", "단모", "단두종", "느긋한", "온순한", "운동량적음", "고집센", "애교많은", "아이와잘맞음", "차분한"],
    imgPath: "bulldog/english"
  },
  {
    id: "border-collie",
    name: "보더콜리",
    en: "Border Collie",
    size: "중형",
    height: "46~56cm",
    weight: "14~22kg",
    life: "12~15년",
    personality: "세계에서 가장 똑똑하며 활동량이 매우 많음",
    desc: "견종 지능 1위로 훈련 능력이 탁월합니다. 목양견 출신이라 엄청난 에너지가 있어 매일 충분한 운동과 두뇌 활동이 필요합니다.",
    tags: ["중형", "중형견", "똑똑한", "지능높음", "훈련잘됨", "활동적", "운동량많음", "산책", "사냥본능", "장모", "털많이빠짐", "충성심", "민감한"],
    imgPath: "collie/border"
  },
  {
    id: "shetland-sheepdog",
    name: "셰틀랜드시프독",
    en: "Shetland Sheepdog",
    size: "중형",
    height: "33~41cm",
    weight: "6~12kg",
    life: "12~14년",
    personality: "총명하고 충성스러우며 예민한 편",
    desc: "미니 콜리 같은 외모의 목양견으로, 지능이 높고 주인에게 매우 충실합니다. 활발하며 경계심이 있어 감시견으로도 적합합니다.",
    tags: ["중형", "중형견", "똑똑한", "지능높음", "훈련잘됨", "활동적", "장모", "손질필요", "충성심", "경계심강함", "털많이빠짐", "민감한"],
    imgPath: null
  },
  {
    id: "whippet",
    name: "휘핏",
    en: "Whippet",
    size: "중형",
    height: "44~51cm",
    weight: "9~18kg",
    life: "12~15년",
    personality: "온화하고 조용하며 순한 성격",
    desc: "미니 그레이하운드로 시속 55km까지 달리는 스프린터입니다. 밖에서는 빠르지만 집 안에서는 조용하고 느긋하게 지냅니다.",
    tags: ["중형", "중형견", "단모", "털잘안빠짐", "조용한", "온순한", "빠름", "순함", "아파트적합", "느긋한", "사냥본능"],
    imgPath: "whippet"
  },
  {
    id: "dalmatian",
    name: "달마시안",
    en: "Dalmatian",
    size: "중형",
    height: "56~61cm",
    weight: "20~32kg",
    life: "11~13년",
    personality: "활발하고 밝으며 인내심이 강함",
    desc: "흰 바탕의 검은 반점 무늬로 유명한 견종입니다. 마차 호위견 출신으로 지구력이 뛰어나며, 활동량이 매우 많은 것이 특징입니다.",
    tags: ["중형", "대형", "단모", "활동적", "운동량많음", "산책", "밝은", "사교적인", "독립적", "아이와잘맞음"],
    imgPath: "dalmatian"
  },
  {
    id: "basenji",
    name: "바센지",
    en: "Basenji",
    size: "중형",
    height: "40~43cm",
    weight: "9~11kg",
    life: "13~14년",
    personality: "독립적이고 영리하며 다소 무뚝뚝함",
    desc: "'짖지 않는 개'로 유명한 아프리카 원산의 견종입니다. 고양이처럼 스스로 몸을 닦고, 독립적이며 조용해 실내 생활에 잘 맞습니다.",
    tags: ["중형", "중형견", "조용한", "안짖는", "단모", "털잘안빠짐", "독립적", "똑똑한", "활동적", "사냥본능", "고집센"],
    imgPath: "basenji"
  },
  {
    id: "basset-hound",
    name: "바셋하운드",
    en: "Basset Hound",
    size: "중형",
    height: "33~38cm",
    weight: "20~29kg",
    life: "10~12년",
    personality: "온순하고 느긋하며 다정한 성격",
    desc: "긴 귀와 처진 눈, 낮은 몸집이 특징적인 후각견입니다. 느긋하고 다정해 가족에게 애정이 깊지만 후각에 이끌리면 고집을 부립니다.",
    tags: ["중형", "중형견", "단모", "느긋한", "온순한", "후각", "사냥본능", "가족친화적", "아이와잘맞음", "아파트적합", "고집센"],
    imgPath: "basset"
  },
  {
    id: "bloodhound",
    name: "블러드하운드",
    en: "Bloodhound",
    size: "대형",
    height: "58~69cm",
    weight: "36~50kg",
    life: "10~12년",
    personality: "온순하고 다정하며 인내심이 강함",
    desc: "후각이 세계 최고 수준으로 미국 경찰도 사용하는 추적견입니다. 온순하고 다정하며, 어린아이에게도 인내심이 많습니다.",
    tags: ["대형", "대형견", "단모", "후각", "사냥본능", "온순한", "아이와잘맞음", "가족친화적", "고집센", "활동적"],
    imgPath: "bloodhound"
  },
  {
    id: "samoyed",
    name: "사모예드",
    en: "Samoyed",
    size: "중형",
    height: "48~59cm",
    weight: "16~30kg",
    life: "12~14년",
    personality: "밝고 다정하며 사람을 좋아함",
    desc: "'웃는 개'라 불리는 하얀 털의 시베리아 썰매견입니다. 사람과 함께 일하며 발전한 견종이라 사교성이 뛰어나고 가족에게 다정합니다.",
    tags: ["중형", "대형", "장모", "손질필요", "흰털", "털많이빠짐", "밝은", "사교적인", "아이와잘맞음", "가족친화적", "활동적", "운동량많음", "온순한"],
    imgPath: "samoyed"
  },
  {
    id: "jindo",
    name: "진돗개",
    en: "Jindo",
    size: "중형",
    height: "45~58cm",
    weight: "16~23kg",
    life: "12~15년",
    personality: "충성심이 매우 강하고 총명하며 자주성이 있음",
    desc: "천연기념물로 지정된 한국의 대표 견종입니다. 주인에 대한 충성심이 뛰어나고 경계심이 강해 훌륭한 감시견입니다.",
    tags: ["중형", "중형견", "단모", "충성심", "경계심강함", "감시견", "똑똑한", "독립적", "활동적", "털많이빠짐", "용감한"],
    imgPath: null
  },
  {
    id: "chow-chow",
    name: "차우차우",
    en: "Chow Chow",
    size: "중형",
    height: "46~56cm",
    weight: "20~32kg",
    life: "9~15년",
    personality: "독립적이고 품위 있으며 고양이 같은 성격",
    desc: "사자 갈기 털과 보라색 혀가 특징인 중국 원산 견종입니다. 독립적이고 진중하며 낯선 사람에게 차갑지만 가족에게는 깊은 애정을 보입니다.",
    tags: ["중형", "중형견", "대형", "장모", "손질필요", "털많이빠짐", "독립적", "차분한", "경계심강함", "감시견", "고집센"],
    imgPath: "chow"
  },
  {
    id: "golden-retriever",
    name: "골든리트리버",
    en: "Golden Retriever",
    size: "대형",
    height: "51~61cm",
    weight: "25~34kg",
    life: "10~12년",
    personality: "매우 온순하고 사교적이며 신뢰감 있음",
    desc: "안내견·치료견으로 세계적으로 사랑받는 견종입니다. 온순하고 지능이 높아 훈련이 잘 되며, 아이들과도 완벽하게 어울립니다.",
    tags: ["대형", "대형견", "온순한", "순함", "사교적인", "아이와잘맞음", "가족친화적", "똑똑한", "훈련잘됨", "장모", "털많이빠짐", "초보자적합", "활동적", "수영"],
    imgPath: "retriever/golden"
  },
  {
    id: "labrador",
    name: "래브라도리트리버",
    en: "Labrador Retriever",
    size: "대형",
    height: "54~62cm",
    weight: "25~36kg",
    life: "10~14년",
    personality: "다정하고 순하며 활발하고 사교적임",
    desc: "세계에서 가장 인기 있는 견종 중 하나로, 안내견과 구조견으로도 활약합니다. 순하고 밝아 초보자에게도 좋은 가족견입니다.",
    tags: ["대형", "대형견", "온순한", "순함", "사교적인", "아이와잘맞음", "가족친화적", "똑똑한", "훈련잘됨", "초보자적합", "단모", "활동적", "운동량많음", "수영"],
    imgPath: "labrador"
  },
  {
    id: "german-shepherd",
    name: "저먼셰퍼드",
    en: "German Shepherd",
    size: "대형",
    height: "55~65cm",
    weight: "22~40kg",
    life: "9~13년",
    personality: "총명하고 용감하며 충성심이 매우 강함",
    desc: "경찰견·군견·탐지견으로 활약하는 만능 작업견입니다. 지능과 충성심이 탁월하며, 올바른 훈련과 사회화가 중요합니다.",
    tags: ["대형", "대형견", "똑똑한", "지능높음", "훈련잘됨", "충성심", "용감한", "경계심강함", "감시견", "경비", "활동적", "운동량많음", "털많이빠짐", "장모"],
    imgPath: "germanshepherd"
  },
  {
    id: "husky",
    name: "시베리안허스키",
    en: "Siberian Husky",
    size: "대형",
    height: "50~60cm",
    weight: "16~27kg",
    life: "12~14년",
    personality: "친근하고 활발하며 독립적인 성격",
    desc: "늑대를 닮은 외모와 하늘색 눈이 매력적인 썰매견입니다. 에너지가 매우 넘치고 사교적이며, 자유분방한 성격으로 유명합니다.",
    tags: ["대형", "대형견", "활동적", "운동량많음", "산책", "에너지넘침", "사교적인", "독립적", "장모", "털많이빠짐", "밝은", "장난기"],
    imgPath: "husky"
  },
  {
    id: "malamute",
    name: "알라스칸말라뮤트",
    en: "Alaskan Malamute",
    size: "대형",
    height: "58~64cm",
    weight: "34~39kg",
    life: "10~14년",
    personality: "다정하고 장난기가 많으며 강한 체력을 보유",
    desc: "허스키보다 더 크고 힘센 썰매견입니다. 힘과 지구력이 뛰어나고 사람에게 우호적이지만, 풍부한 운동량이 필수입니다.",
    tags: ["대형", "대형견", "활동적", "운동량많음", "산책", "에너지넘침", "장모", "털많이빠짐", "사교적인", "가족친화적", "아이와잘맞음"],
    imgPath: "malamute"
  },
  {
    id: "doberman",
    name: "도베르만",
    en: "Doberman Pinscher",
    size: "대형",
    height: "61~72cm",
    weight: "30~45kg",
    life: "10~13년",
    personality: "총명하고 충성스러우며 경계심이 강함",
    desc: "세련된 실루엣의 대표적인 경비견입니다. 지능이 높고 훈련이 잘 되며, 가족에게 깊은 애정을 보이는 반면 강한 경계 본능이 있습니다.",
    tags: ["대형", "대형견", "똑똑한", "지능높음", "훈련잘됨", "경계심강함", "감시견", "경비", "충성심", "단모", "활동적", "운동량많음", "용감한"],
    imgPath: "doberman"
  },
  {
    id: "rottweiler",
    name: "로트바일러",
    en: "Rottweiler",
    size: "대형",
    height: "56~69cm",
    weight: "35~60kg",
    life: "8~11년",
    personality: "용감하고 자신감 있으며 가족에 대한 보호 본능이 강함",
    desc: "강력한 체격의 경비견·군견입니다. 침착하고 자신감 있으며 올바른 사회화와 확실한 리더십이 필요한 견종입니다.",
    tags: ["대형", "대형견", "경계심강함", "감시견", "경비", "용감한", "충성심", "단모", "활동적", "운동량많음", "가족친화적"],
    imgPath: "rottweiler"
  },
  {
    id: "great-dane",
    name: "그레이트데인",
    en: "Great Dane",
    size: "대형",
    height: "71~81cm",
    weight: "45~80kg",
    life: "7~10년",
    personality: "차분하고 온순하며 '다정한 거인'",
    desc: "세계에서 가장 큰 견종 중 하나입니다. 크기와 달리 온순하고 다정해 '아폴로 오브 독스'라 불리며, 가족과 함께 있는 것을 좋아합니다.",
    tags: ["대형", "대형견", "온순한", "차분한", "가족친화적", "아이와잘맞음", "단모", "큰", "온화", "운동량적음"],
    imgPath: "dane/great"
  },
  {
    id: "st-bernard",
    name: "세인트버나드",
    en: "Saint Bernard",
    size: "대형",
    height: "65~80cm",
    weight: "50~90kg",
    life: "8~10년",
    personality: "다정하고 인내심이 많으며 온화함",
    desc: "스위스 알프스의 구조견 출신 거대견입니다. 매우 온화하고 인내심이 강해 아이들과도 잘 지내는 다정한 거인입니다.",
    tags: ["대형", "대형견", "온순한", "온화", "아이와잘맞음", "가족친화적", "큰", "장모", "털많이빠짐", "차분한", "운동량적음"],
    imgPath: "stbernard"
  },
  {
    id: "bernese-mountain-dog",
    name: "버니즈마운틴독",
    en: "Bernese Mountain Dog",
    size: "대형",
    height: "58~70cm",
    weight: "36~52kg",
    life: "7~10년",
    personality: "다정하고 온순하며 가족에게 헌신적",
    desc: "스위스의 삼색 털 목장견입니다. 온순하고 다정하며 아이들과 잘 지내지만, 더위에 약해 시원한 환경이 필요합니다.",
    tags: ["대형", "대형견", "온순한", "아이와잘맞음", "가족친화적", "장모", "털많이빠짐", "활동적", "큰", "온화"],
    imgPath: "mountain/bernese"
  },
  {
    id: "great-pyrenees",
    name: "그레이트피레니즈",
    en: "Great Pyrenees",
    size: "대형",
    height: "65~81cm",
    weight: "39~55kg",
    life: "10~12년",
    personality: "차분하고 인내심이 강하며 보호 본능이 뛰어남",
    desc: "눈처럼 하얀 털의 대형 가축 보호견입니다. 침착하고 인내심이 강하며, 독립적이지만 가족을 지키려는 강한 본능이 있습니다.",
    tags: ["대형", "대형견", "흰털", "장모", "손질필요", "털많이빠짐", "차분한", "감시견", "경계심강함", "독립적", "큰", "아이와잘맞음"],
    imgPath: "pyrenees"
  },
  {
    id: "newfoundland",
    name: "뉴펀들랜드",
    en: "Newfoundland",
    size: "대형",
    height: "63~71cm",
    weight: "45~70kg",
    life: "8~10년",
    personality: "온화하고 다정하며 수영 본능이 뛰어남",
    desc: "물 구조견으로 유명한 거대견입니다. 물발가락이 있어 수영을 잘하며, 매우 온화하고 다정해 '천사의 거인'이라 불립니다.",
    tags: ["대형", "대형견", "온순한", "온화", "아이와잘맞음", "가족친화적", "수영", "장모", "손질필요", "털많이빠짐", "큰", "차분한"],
    imgPath: "newfoundland"
  },
  {
    id: "greyhound",
    name: "그레이하운드",
    en: "Greyhound",
    size: "대형",
    height: "68~76cm",
    weight: "27~40kg",
    life: "10~14년",
    personality: "온순하고 차분하며 다정한 성격",
    desc: "시속 70km로 달리는 세계에서 가장 빠른 견종입니다. 의외로 집 안에서는 '소파 감자'처럼 조용하고 느긋하게 지냅니다.",
    tags: ["대형", "대형견", "빠름", "단모", "털잘안빠짐", "조용한", "온순한", "느긋한", "차분한", "사냥본능", "민감한"],
    imgPath: "greyhound"
  },
  {
    id: "boxer",
    name: "복서",
    en: "Boxer",
    size: "대형",
    height: "53~63cm",
    weight: "25~32kg",
    life: "10~12년",
    personality: "장난기가 많고 밝으며 가족을 향한 애정이 깊음",
    desc: "근육질 몸매와 장난기 넘치는 성격이 매력입니다. 가족에게 매우 다정하고 아이들과 잘 지내며, 경계심도 있어 좋은 감시견입니다.",
    tags: ["대형", "대형견", "단모", "활동적", "운동량많음", "장난기", "가족친화적", "아이와잘맞음", "감시견", "경계심강함", "용감한", "밝은"],
    imgPath: "boxer"
  },
  {
    id: "tibetan-mastiff",
    name: "티베탄마스티프",
    en: "Tibetan Mastiff",
    size: "대형",
    height: "61~76cm",
    weight: "45~72kg",
    life: "10~14년",
    personality: "독립적이고 고집이 세며 보호 본능이 강함",
    desc: "히말라야의 가축 보호견으로, 풍성한 갈기가 사자를 닮았습니다. 독립적이고 영역 본능이 강해 경험이 있는 주인이 필요합니다.",
    tags: ["대형", "대형견", "장모", "손질필요", "털많이빠짐", "감시견", "경계심강함", "독립적", "고집센", "큰", "경비"],
    imgPath: "mastiff/tibetan"
  },
  {
    id: "bull-mastiff",
    name: "불마스티프",
    en: "Bullmastiff",
    size: "대형",
    height: "61~69cm",
    weight: "41~59kg",
    life: "8~10년",
    personality: "용감하고 충성스러우며 낮에는 온순함",
    desc: "도둑을 잡기 위해 만들어진 영국의 경비견입니다. 힘이 세고 용감하며, 가족에게는 다정하고 순한 모습을 보입니다.",
    tags: ["대형", "대형견", "감시견", "경계심강함", "경비", "용감한", "충성심", "단모", "가족친화적", "큰", "차분한"],
    imgPath: "mastiff/bull"
  },
  {
    id: "rhodesian-ridgeback",
    name: "로디지아리지백",
    en: "Rhodesian Ridgeback",
    size: "대형",
    height: "61~69cm",
    weight: "29~41kg",
    life: "10~12년",
    personality: "용감하고 독립적이며 가족에게 애정이 깊음",
    desc: "아프리카에서 사자 사냥을 도왔던 견종으로, 등의 역방향 갈기가 특징입니다. 체력이 뛰어나고 주인에게 깊은 충성심을 보입니다.",
    tags: ["대형", "대형견", "단모", "활동적", "운동량많음", "용감한", "독립적", "사냥본능", "충성심", "큰"],
    imgPath: "ridgeback/rhodesian"
  },
  {
    id: "borzoi",
    name: "보르조이",
    en: "Borzoi",
    size: "대형",
    height: "66~85cm",
    weight: "27~48kg",
    life: "9~14년",
    personality: "우아하고 조용하며 애정이 깊음",
    desc: "러시아 귀족이 사냥용으로 키운 세이프하운드입니다. 길고 우아한 몸과 조용한 성격으로, 집에서는 온화한 반려견이 됩니다.",
    tags: ["대형", "대형견", "장모", "손질필요", "조용한", "온순한", "빠름", "사냥본능", "우아한", "민감한", "큰"],
    imgPath: "borzoi"
  },
  {
    id: "saluki",
    name: "살루키",
    en: "Saluki",
    size: "대형",
    height: "58~71cm",
    weight: "18~27kg",
    life: "12~14년",
    personality: "우아하고 독립적이며 온순함",
    desc: "고대 이집트 시절부터 이어진 세계에서 가장 오래된 견종 중 하나입니다. 우아하고 민첩하며 조용하고 차분한 성격입니다.",
    tags: ["대형", "대형견", "빠름", "조용한", "온순한", "독립적", "사냥본능", "민감한", "단모", "큰"],
    imgPath: "saluki"
  },
  {
    id: "irish-wolfhound",
    name: "아이리시울프하운드",
    en: "Irish Wolfhound",
    size: "대형",
    height: "76~90cm",
    weight: "48~70kg",
    life: "6~10년",
    personality: "온화하고 다정하며 점잖은 성격",
    desc: "세계에서 키가 가장 큰 견종 중 하나입니다. 늑대 사냥견 출신이지만 성격은 매우 온화하고 다정해 가족과 아이들에게 헌신적입니다.",
    tags: ["대형", "대형견", "장모", "손질필요", "온화", "아이와잘맞음", "가족친화적", "큰", "조용한", "사냥본능"],
    imgPath: "wolfhound/irish"
  },
  {
    id: "weimaraner",
    name: "위마라너",
    en: "Weimaraner",
    size: "대형",
    height: "56~69cm",
    weight: "25~40kg",
    life: "11~14년",
    personality: "활발하고 사람을 매우 좋아하며 애착이 강함",
    desc: "'회색 유령'이라 불리는 독일의 사냥견입니다. 은회색 털과 호박색 눈이 매력적이며, 에너지가 많아 주인과 함께하는 운동이 필요합니다.",
    tags: ["대형", "대형견", "단모", "활동적", "운동량많음", "산책", "사냥본능", "가족친화적", "애교많은", "에너지넘침", "큰"],
    imgPath: "weimaraner"
  },
  {
    id: "vizsla",
    name: "비즐라",
    en: "Vizsla",
    size: "대형",
    height: "53~64cm",
    weight: "18~30kg",
    life: "12~15년",
    personality: "다정하고 민감하며 사람과의 유대가 깊음",
    desc: "헝가리의 우아한 포인팅견입니다. 황금빛 동털이 매력적이며, 주인과의 유대가 매우 깊어 '벨크로견'이라 불립니다.",
    tags: ["대형", "대형견", "단모", "털잘안빠짐", "활동적", "운동량많음", "산책", "사냥본능", "애교많은", "민감한", "큰"],
    imgPath: "vizsla"
  }
];

const SYNONYMS = {
  "작은": ["소형"],
  "작": ["소형", "작은"],
  "소형견": [],
  "소형": ["소형견"],
  "커다란": ["대형"],
  "큰": ["대형", "대형견"],
  "대형견": [],
  "대형": ["대형견"],
  "중형견": [],
  "중형": ["중형견"],
  "활동적인": ["활동적"],
  "활동": ["활동적"],
  "에너지": ["활동적", "에너지넘침"],
  "운동": ["운동량많음", "활동적"],
  "산책": ["산책", "활동적"],
  "똑똑": ["똑똑한", "지능높음"],
  "똑똑한": ["지능높음", "훈련잘됨"],
  "똑똑하": ["똑똑한"],
  "지능": ["지능높음", "똑똑한"],
  "온순": ["온순한", "순함"],
  "온순한": ["순함"],
  "순한": ["순함"],
  "얌전": ["조용한", "온순한"],
  "온화한": ["온화"],
  "온화": [],
  "사교": ["사교적인"],
  "사교적인": ["친화적"],
  "친근": ["친화적", "사교적인"],
  "애교": ["애교많은"],
  "애교많": ["애교많은"],
  "아파트": ["아파트적합", "실내적합"],
  "실내": ["실내적합", "아파트적합"],
  "초보": ["초보자적합"],
  "경계": ["경계심강함"],
  "감시": ["감시견"],
  "경비": ["감시견", "경계심강함"],
  "가드": ["감시견", "경계심강함"],
  "지키기": ["감시견", "경계심강함"],
  "집을지키": ["감시견"],
  "아이": ["아이와잘맞음"],
  "아이랑": ["아이와잘맞음"],
  "어린이": ["아이와잘맞음"],
  "아가": ["아이와잘맞음"],
  "가족": ["가족친화적"],
  "털빠짐": ["털잘안빠짐"],
  "털빠지": ["털잘안빠짐"],
  "탈모": ["털잘안빠짐"],
  "털관리": ["손질필요", "장모"],
  "장모": ["손질필요"],
  "단모": [],
  "안짖는": ["조용한"],
  "짖지": ["조용한"],
  "조용": ["조용한"],
  "귀여운": ["귀여운"],
  "귀엽": ["귀여운"],
  "오래사는": ["장수"],
  "오래": ["장수"],
  "장수": [],
  "훈련": ["훈련잘됨"],
  "충성": ["충성심"],
  "용감": ["용감한"],
  "고집": ["고집센"],
  "느긋": ["느긋한"],
  "차분": ["차분한"],
  "느린": ["운동량적음", "느긋한"],
  "수영": ["수영"],
  "빠른": ["빠름"],
  "빨리": ["빠름"],
  "달리기": ["빠름", "활동적"],
  "후각": ["후각"],
  "냄새": ["후각"],
  "장난": ["장난기"],
  "민감": ["민감한"]
};

const LABEL_MAP = {
  "chihuahua": "chihuahua",
  "maltese dog": "maltese",
  "shih-tzu": "shih-tzu",
  "pekinese": "pekingese",
  "papillon": "papillon",
  "basset": "basset-hound",
  "beagle": "beagle",
  "bloodhound": "bloodhound",
  "italian greyhound": "italian-greyhound",
  "whippet": "whippet",
  "boston bull": "boston-terrier",
  "french bulldog": "french-bulldog",
  "pug": "pug",
  "great dane": "great-dane",
  "saint bernard": "st-bernard",
  "labrador retriever": "labrador",
  "golden retriever": "golden-retriever",
  "german shepherd": "german-shepherd",
  "siberian husky": "husky",
  "eskimo dog": "husky",
  "malamute": "malamute",
  "samoyed": "samoyed",
  "pomeranian": "pomeranian",
  "toy poodle": "poodle",
  "miniature poodle": "poodle",
  "standard poodle": "poodle",
  "yorkshire terrier": "yorkshire-terrier",
  "west highland white terrier": "west-highland",
  "lhasa": "lhasa-apso",
  "newfoundland": "newfoundland",
  "great pyrenees": "great-pyrenees",
  "tibetan mastiff": "tibetan-mastiff",
  "bull mastiff": "bull-mastiff",
  "miniature pinscher": "min-pin",
  "standard schnauzer": "schnauzer",
  "miniature schnauzer": "schnauzer",
  "giant schnauzer": "schnauzer",
  "cocker spaniel": "cocker-spaniel",
  "pembroke": "welsh-corgi",
  "cardigan": "welsh-corgi",
  "dalmatian": "dalmatian",
  "basenji": "basenji",
  "chow": "chow-chow",
  "rottweiler": "rottweiler",
  "doberman": "doberman",
  "border collie": "border-collie",
  "shetland sheepdog": "shetland-sheepdog",
  "collie": "shetland-sheepdog",
  "bernese mountain dog": "bernese-mountain-dog",
  "boxer": "boxer",
  "rhodesian ridgeback": "rhodesian-ridgeback",
  "borzoi": "borzoi",
  "saluki": "saluki",
  "greyhound": "greyhound",
  "irish wolfhound": "irish-wolfhound",
  "weimaraner": "weimaraner",
  "vizsla": "vizsla",
  "old english sheepdog": "shetland-sheepdog",
  "maltese terrier": "maltese",
  "maltese": "maltese",
  "pekingese": "pekingese",
  "peke": "pekingese",
  "husky": "husky",
  "malemute": "malamute",
  "alsatian": "german-shepherd",
  "german police dog": "german-shepherd",
  "doberman pinscher": "doberman",
  "st bernard": "st-bernard",
  "coach dog": "dalmatian",
  "carriage dog": "dalmatian",
  "pug-dog": "pug",
  "basset hound": "basset-hound",
  "sleuthhound": "bloodhound",
  "russian wolfhound": "borzoi",
  "gazelle hound": "saluki",
  "deerhound": "greyhound",
  "scottish deerhound": "greyhound",
  "newfoundland dog": "newfoundland",
  "samoyede": "samoyed",
  "chow chow": "chow-chow",
  "pembroke welsh corgi": "welsh-corgi",
  "cardigan welsh corgi": "welsh-corgi"
};

const DOG_LABELS = [
  "chihuahua", "japanese spaniel", "maltese dog", "pekinese", "shih-tzu", "blenheim spaniel",
  "papillon", "toy terrier", "rhodesian ridgeback", "afghan hound", "basset", "beagle",
  "bloodhound", "bluetick", "black-and-tan coonhound", "walker hound", "english foxhound",
  "redbone", "borzoi", "irish wolfhound", "italian greyhound", "whippet", "ibizan hound",
  "norwegian elkhound", "otterhound", "saluki", "scottish deerhound", "weimaraner",
  "staffordshire bullterrier", "american staffordshire terrier", "bedlington terrier",
  "border terrier", "kerry blue terrier", "irish terrier", "norfolk terrier", "norwich terrier",
  "yorkshire terrier", "wire-haired fox terrier", "lakeland terrier", "sealyham terrier",
  "airedale", "cairn", "australian terrier", "dandie dinmont", "boston bull",
  "miniature schnauzer", "giant schnauzer", "standard schnauzer", "scotch terrier",
  "tibetan terrier", "silky terrier", "soft-coated wheaten terrier", "west highland white terrier",
  "lhasa", "flat-coated retriever", "curly-coated retriever", "golden retriever",
  "labrador retriever", "chesapeake bay retriever", "german shorthaired pointer",
  "english setter", "irish setter", "gordon setter", "brittany spaniel", "clumber",
  "english springer", "welsh springer spaniel", "cocker spaniel", "sussex spaniel",
  "irish water spaniel", "kuvasz", "schipperke", "groenendael", "malinois", "briard",
  "kelpie", "komondor", "old english sheepdog", "shetland sheepdog", "collie",
  "border collie", "bouvier des flandres", "rottweiler", "german shepherd", "doberman",
  "miniature pinscher", "greater swiss mountain dog", "bernese mountain dog", "appenzeller",
  "entlebucher", "boxer", "bull mastiff", "tibetan mastiff", "french bulldog", "great dane",
  "saint bernard", "eskimo dog", "malamute", "siberian husky", "dalmatian", "affenpinscher",
  "basenji", "pug", "leonberg", "newfoundland", "great pyrenees", "samoyed", "pomeranian",
  "chow", "keeshond", "brabancon griffon", "pembroke", "cardigan", "toy poodle",
  "miniature poodle", "standard poodle", "mexican hairless"
];

function getBreedById(id) {
  return BREEDS.find(function (b) { return b.id === id; }) || null;
}

function mapLabelToBreedId(label) {
  var seg0 = label.split(",")[0].trim().toLowerCase();
  return LABEL_MAP[seg0] || null;
}

function isDogLabel(label) {
  var seg0 = label.split(",")[0].trim().toLowerCase();
  return DOG_LABELS.indexOf(seg0) !== -1;
}
